GET http://localhost:13000/heartbeat


###


GET http://localhost:13000/auth/getToken
Content-Type: application/json

{
  "userName": "Bob",
  "password": "12345"
}

###
GET http://localhost:13000/auth/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkJvYiIsInBhc3N3b3JkIjoiMTIzNDUiLCJpYXQiOjE2MTExOTg0OTB9.w2o7js4CY5dNNxKvF-dpk_w27e9x2tmxCNik3_ZxOLU