version: "2"
services:
  node_express_example:
    image: "docker_node_example:latest"
    user: "node"
    environment:
      - NODE_ENV=production
    ports:
      - "9001:9001"
    command: "npm start"
  monogo:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example